In [4]:
!pip3 install transformers --user

  Using cached transformers-4.38.2-py3-none-any.whl.metadata (130 kB)
  Using cached tokenizers-0.15.2-cp312-none-win_amd64.whl.metadata (6.8 kB)
Using cached transformers-4.38.2-py3-none-any.whl (8.5 MB)
Using cached tokenizers-0.15.2-cp312-none-win_amd64.whl (2.2 MB)


In [2]:
!pip3 install faiss-cpu

In [5]:
!pip3 install -U scikit-learn scipy matplotlib --user

  Using cached scikit_learn-1.4.1.post1-cp312-cp312-win_amd64.whl.metadata (11 kB)
  Using cached scipy-1.12.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
Using cached scikit_learn-1.4.1.post1-cp312-cp312-win_amd64.whl (10.6 MB)
Using cached scipy-1.12.0-cp312-cp312-win_amd64.whl (45.8 MB)


In [6]:
!pip3 install networkx==3.1 --user
!pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu --user

   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.1 MB ? eta -:--:--
   - -------------------------------------- 0.1/2.1 MB 1.3 MB/s eta 0:00:02
   --- ------------------------------------ 0.2/2.1 MB 1.3 MB/s eta 0:00:02
   --- ------------------------------------ 0.2/2.1 MB 1.2 MB/s eta 0:00:02
   ----- ---------------------------------- 0.3/2.1 MB 1.6 MB/s eta 0:00:02
   -------- ------------------------------- 0.4/2.1 MB 1.5 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.9 MB/s eta 0:00:01
   ------------ --------------------------- 0.7/2.1 MB 1.8 MB/s eta 0:00:01
   ---------------- ----------------------- 0.9/2.1 MB 2.3 MB/s eta 0:00:01
   ---------------------- ----------------- 1.2/2.1 MB 2.6 MB/s eta 0:00:01
   ---------------------------------- ----- 1.8/2.1 MB 3.6 MB/s eta 0:00:01
   ------------------------------------ --- 1.9/2.1 MB 3.4 MB/s eta 0:00:01
   -----------------------

In [1]:
from transformers import AutoTokenizer, AutoModel
import torch
import numpy as np

c:\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
tokenizer = AutoTokenizer.from_pretrained('BAAI/bge-small-en-v1.5') # you can change the model here
model = AutoModel.from_pretrained('BAAI/bge-small-en-v1.5')

In [72]:
import json

sentences = []

file_path = 'sampled_data.json'

with open(file_path, 'r') as file:
    data = json.load(file)

if isinstance(data, list):
    record_count = len(data)
    for record in data:
        sentences.append(record['Data'])

In [73]:
data[0]["Name"]
data[0]["URL"]
data[0]["Image_Serialized"]

'PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVuIj4KPG1ldGEgY2hhcnNldD0idXRmLTgiPgo8dGl0bGU+V2lraW1lZGlhIEVycm9yPC90aXRsZT4KPHN0eWxlPgoqIHsgbWFyZ2luOiAwOyBwYWRkaW5nOiAwOyB9CmJvZHkgeyBiYWNrZ3JvdW5kOiAjZmZmOyBmb250OiAxNXB4LzEuNiBzYW5zLXNlcmlmOyBjb2xvcjogIzMzMzsgfQouY29udGVudCB7IG1hcmdpbjogNyUgYXV0byAwOyBwYWRkaW5nOiAyZW0gMWVtIDFlbTsgbWF4LXdpZHRoOiA2NDBweDsgfQouZm9vdGVyIHsgY2xlYXI6IGJvdGg7IG1hcmdpbi10b3A6IDE0JTsgYm9yZGVyLXRvcDogMXB4IHNvbGlkICNlNWU1ZTU7IGJhY2tncm91bmQ6ICNmOWY5Zjk7IHBhZGRpbmc6IDJlbSAwOyBmb250LXNpemU6IDAuOGVtOyB0ZXh0LWFsaWduOiBjZW50ZXI7IH0KaW1nIHsgZmxvYXQ6IGxlZnQ7IG1hcmdpbjogMCAyZW0gMmVtIDA7IH0KYSBpbWcgeyBib3JkZXI6IDA7IH0KaDEgeyBtYXJnaW4tdG9wOiAxZW07IGZvbnQtc2l6ZTogMS4yZW07IH0KLmNvbnRlbnQtdGV4dCB7IG92ZXJmbG93OiBoaWRkZW47IG92ZXJmbG93LXdyYXA6IGJyZWFrLXdvcmQ7IHdvcmQtd3JhcDogYnJlYWstd29yZDsgLXdlYmtpdC1oeXBoZW5zOiBhdXRvOyAtbW96LWh5cGhlbnM6IGF1dG87IC1tcy1oeXBoZW5zOiBhdXRvOyBoeXBoZW5zOiBhdXRvOyB9CnAgeyBtYXJnaW46IDAuN2VtIDAgMWVtIDA7IH0KYSB7IGNvbG9yOiAjMDY0NWFkOyB0ZXh0LWRlY29yYXRpb246IG5vbmU

In [74]:
print("Before: ",len(sentences))
sentences = [sentence for sentence in sentences if sentence is not None]
print("After: ",len(sentences))

Before:  50
After:  50


In [77]:
sentences_ = []
sentence_to_index_mapper = {}
for idx,sentence in enumerate(sentences):
  words = sentence.split(" ")
  sentence_to_index_mapper[idx] = []
  for i in range(0, len(words), 350):
    sentence_to_index_mapper[idx].append(len(sentences_))
    if i+350<len(words):
      sentences_.append(words[i:i+350])
    else:
      sentences_.append(words[i:])

In [78]:
sentence_to_index_mapper

{0: [0, 1, 2, 3, 4, 5, 6, 7],
 1: [8, 9, 10, 11, 12, 13, 14, 15],
 2: [16, 17, 18, 19, 20],
 3: [21, 22, 23, 24],
 4: [25, 26, 27, 28, 29, 30, 31, 32, 33],
 5: [34, 35, 36, 37, 38, 39],
 6: [40, 41, 42, 43, 44, 45],
 7: [46, 47, 48, 49, 50, 51],
 8: [52, 53, 54, 55, 56, 57],
 9: [58, 59, 60, 61, 62, 63, 64, 65],
 10: [66, 67, 68, 69],
 11: [70, 71, 72],
 12: [73, 74, 75, 76, 77],
 13: [78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88],
 14: [89, 90, 91, 92, 93, 94, 95],
 15: [96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
 16: [110, 111, 112, 113, 114, 115, 116],
 17: [117, 118, 119],
 18: [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132],
 19: [133, 134, 135],
 20: [136, 137, 138, 139, 140, 141, 142, 143],
 21: [144, 145, 146],
 22: [147, 148, 149, 150, 151],
 23: [152, 153, 154, 155, 156, 157, 158, 159, 160],
 24: [161, 162, 163, 164],
 25: [165, 166, 167, 168, 169, 170, 171, 172, 173],
 26: [174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 18

In [97]:
# initialize dictionary to store tokenized sentences
tokens = {'input_ids': [], 'attention_mask': []}

for sentence in sentences_:
    # encode each sentence and append to dictionary
    new_tokens = tokenizer.encode_plus(sentence, max_length=512,
                                       truncation=True, padding='max_length',
                                       return_tensors='pt', is_split_into_words=True)
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])

In [46]:
torch.save(tokens, 'tokens.pt')

In [98]:
tensor_list = []
batch_size = 100
dict_size = len(tokens['input_ids'])
for i in range(0, dict_size, batch_size):
    if i+batch_size<=dict_size:
        batch = {
            'input_ids': tokens['input_ids'][i:i+batch_size],
            'attention_mask': tokens['attention_mask'][i:i+batch_size]
        }
    else:
        batch = {
            'input_ids': tokens['input_ids'][i:],
            'attention_mask': tokens['attention_mask'][i:]
        }
    batch['input_ids'] = torch.stack(batch['input_ids'])
    batch['attention_mask'] = torch.stack(batch['attention_mask'])
    with torch.no_grad():
        outputs = model(**batch)
    embeddings = outputs.last_hidden_state
    tensor_list.append(embeddings)
result_tensor = torch.cat(tensor_list, dim=0)
print(result_tensor.shape)

torch.Size([376, 512, 384])


In [91]:
embeddings = outputs.last_hidden_state
torch.save(embeddings, 'embeddings.pt')
embeddings.shape

torch.Size([76, 512, 384])

In [92]:
embeddings

tensor([[[-2.2981e-01,  2.3297e-01,  1.4244e-01,  ..., -7.9081e-01,
           7.5423e-01,  7.0630e-02],
         [-4.7586e-01,  4.6700e-02,  1.4817e-01,  ..., -3.1124e-01,
           9.6563e-02, -1.6158e-01],
         [-3.2879e-01,  2.4020e-01,  3.6780e-01,  ..., -2.8555e-01,
           3.3585e-01, -6.8076e-01],
         ...,
         [-1.2176e-01,  4.8976e-01, -2.1116e-01,  ..., -2.1510e-02,
           1.0274e+00, -7.2901e-01],
         [-2.2987e-01,  2.7697e-01,  7.9817e-01,  ..., -3.9862e-01,
           4.4009e-02, -1.8250e-01],
         [-2.2980e-01,  2.3298e-01,  1.4244e-01,  ..., -7.9082e-01,
           7.5426e-01,  7.0605e-02]],

        [[-4.5248e-01,  3.8121e-01, -4.3810e-01,  ..., -3.2218e-01,
           3.9332e-03, -1.3900e-01],
         [-5.5776e-01, -6.0664e-02, -2.5662e-01,  ..., -6.0388e-01,
          -2.1968e-01, -5.2597e-01],
         [-3.8085e-01,  1.8319e-01, -3.0191e-01,  ..., -2.7485e-01,
           4.5874e-01, -2.4634e-01],
         ...,
         [-1.4689e-01,  4

After we have produced our dense vectors embeddings, we need to perform a mean pooling operation to create a single vector encoding (the sentence embedding). To do this mean pooling operation, we will need to multiply each value in our embeddings tensor by its respective attention_mask value — so that we ignore non-real tokens.

In [70]:
tokens_ = torch.load('tokens.pt')

In [71]:
type(tokens_)

dict

In [69]:
a,b = tokens_.keys()
print(tokens_[a][0].shape)
print(tokens_[b][0].shape)

torch.Size([512])
torch.Size([512])


In [60]:
keys = tokens_.keys()
tokens__={
    keys[0]:tokens_[keys[0]][:100],
    keys[1]:tokens_[keys[1]][:100],
}

TypeError: 'dict_keys' object is not subscriptable

In [99]:
tokens['input_ids'] = torch.stack(tokens['input_ids'])
tokens['attention_mask'] = torch.stack(tokens['attention_mask'])

In [100]:
# resize our attention_mask tensor:
attention_mask = tokens['attention_mask']
attention_mask.shape

torch.Size([376, 512])

In [103]:
mask = attention_mask.unsqueeze(-1).expand(result_tensor.size()).float()
mask.shape

torch.Size([376, 512, 384])

Each vector above represents a single token attention mask - each token now has a vector of size 768 representing it's attention_mask status. Then we multiply the two tensors to apply the attention mask:

In [104]:
embeddings = result_tensor

In [105]:
masked_embeddings = embeddings * mask
masked_embeddings.shape

torch.Size([376, 512, 384])

"Mean Pooling" starts

In [106]:
# Then we sum the remained of the embeddings along axis 1, because we want to reduce the 512 tokens to 1 dimension
summed = torch.sum(masked_embeddings, 1)
summed.shape

torch.Size([376, 384])

we want to count only those values that we want to give attention
then divide by the sum to get the mean

In [107]:
# clamp returns the same tensor with a range given, clamp is used to replace the zeros to a very minimal value
# to avoid divide by zero error
summed_mask = torch.clamp(mask.sum(1), min=1e-9)
summed_mask.shape

torch.Size([376, 384])

Finally, we calculate the mean as the sum of the embedding activations summed divided by the number of values that should be given attention in each position `summed_mask`:

In [108]:
mean_pooled = summed / summed_mask

`mean_pooled` is the final "dense representation" of the sentences, note that mean_pooled contains all representations for all sentences together

In [109]:
mean_pooled

tensor([[-1.4918e-01,  3.9104e-01,  4.9015e-01,  ..., -4.6088e-01,
          1.9132e-01, -1.6625e-01],
        [-1.1397e-02, -6.3050e-04,  3.1855e-01,  ..., -6.3042e-01,
          5.5852e-01,  1.9515e-01],
        [-1.4106e-01, -1.7009e-01,  6.1465e-01,  ..., -5.6765e-01,
          1.0008e+00, -4.3195e-01],
        ...,
        [-6.2880e-01,  4.5858e-01,  2.3119e-01,  ..., -2.4954e-01,
          1.2460e-01,  4.9768e-02],
        [-7.4174e-01,  2.4681e-01, -3.0220e-02,  ...,  6.5376e-02,
          4.7862e-01,  3.6719e-03],
        [-2.5363e-01,  4.6797e-02, -1.1548e-01,  ..., -7.6987e-01,
          6.3824e-01,  1.1025e-01]])

## Cosine Similarity

In [112]:
def convert_to_embedding(query):
    tokens = {'input_ids': [], 'attention_mask': []}
    new_tokens = tokenizer.encode_plus(query, max_length=512,
                                       truncation=True, padding='max_length',
                                       return_tensors='pt')
    tokens['input_ids'].append(new_tokens['input_ids'][0])
    tokens['attention_mask'].append(new_tokens['attention_mask'][0])
    tokens['input_ids'] = torch.stack(tokens['input_ids'])
    tokens['attention_mask'] = torch.stack(tokens['attention_mask'])
    with torch.no_grad():
        outputs = model(**tokens)
    embeddings = outputs.last_hidden_state
    attention_mask = tokens['attention_mask']
    mask = attention_mask.unsqueeze(-1).expand(embeddings.size()).float()
    masked_embeddings = embeddings * mask
    summed = torch.sum(masked_embeddings, 1)
    summed_mask = torch.clamp(mask.sum(1), min=1e-9)
    mean_pooled = summed / summed_mask
    
    return mean_pooled[0] # assuming query is a single sentence
    

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [113]:
query = "Quantum"
query_embedding = convert_to_embedding(query)

In [114]:
mean_pooled.shape

torch.Size([376, 384])

In [26]:
cos = torch.nn.CosineSimilarity()
sim = cos(query_embedding, mean_pooled)
sim

tensor([0.1189, 0.2486, 0.1139, 0.1814])

# FAISS

In [110]:
import faiss                   # make faiss available
index = faiss.IndexFlatIP(384)   # build the index
print(index.is_trained)
index.add(mean_pooled)                  # add vectors to the index
print(index.ntotal)

True
376


In [111]:
mean_pooled.shape

torch.Size([376, 384])

In [115]:
query_embedding.shape

torch.Size([384])

In [ ]:
D, I = index.search(query_embedding[None, :], 1) # None dimension is added because we only have one query against 4 documents

In [36]:
D

array([[35.04268]], dtype=float32)

In [37]:
I

array([[1]])

In [41]:
faiss.write_index(index,"sample_code.index")

In [42]:
index_loaded = faiss.read_index("sample_code.index")

In [43]:
D, I = index_loaded.search(query_embedding[None, :], 4)

In [44]:
D

array([[35.04268 , 26.346306, 17.326878, 14.138208]], dtype=float32)

In [45]:
I

array([[1, 3, 0, 2]])